version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
     
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xms512m -Xmx1200m
      TERM: dumb

    steps:
      - checkout
      - run: ./mvnw -pl backend clean install
