env:
  browser: true
  node: true
  es6: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-uses-react: 'error'
  react/jsx-uses-vars: 'error'
settings:
  react:
    createClass: "createReactClass"
    pragma: "React"
    version: "detect"
    flowVersion: "0.53"
